service: happiness-index

package:
  artifact: build/libs/happiness-index-dev-all.jar

custom:
  environment: ${file(./config/environment.json):${self:provider.stage}}

provider:
  name: aws
  runtime: java11
  stage: ${opt:stage, "dev"}
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:custom.environment.bucketName}/*

functions:
  happiness:
    handler: happiness.infrastructure.HappinessHandler
    events:
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      HAPPINESS_BUCKET_NAME: ${self:custom.environment.bucketName}

resources:
  Resources:
    HappinessBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.environment.bucketName}