service: happiness-index

package:
  artifact: build/libs/happiness-index-dev-all.jar

custom:
  bucketName: happiness-index-temp

provider:
  name: aws
  runtime: java11
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:PutObject"
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*

functions:
  happiness:
    handler: happiness.infrastructure.HappinessHandler
    events:
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      HAPPINESS_BUCKET_NAME: "happiness-index-temp"

resources:
  Resources:
    HappinessBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}