name: RELEASE
on:
  push:
    tags:
      - release*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: "PROD: unit tests"
      run: ./gradlew clean unitTest -Pstage=prod

    - name: "PROD: deploy"
      run: ./gradlew clean localDependencyDeploy --stacktrace -Pstage=PROD
